version: '3'

services:
    web:
        container_name: pruebatecnicadocker
        restart: always
        build: .
        command: npm run start
        ports:
            - "3000:3000"
        links: 
          - mongo
        volumes:
          - .:/app
    mongo: 
        container_name: mongodb
        image: mongo
        ports: 
            - "27018:27017"

